# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBaiduSearchHelloWorld():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_baiduSearchHelloWorld(self):
    for i in range(0, 5):
      self.driver.get("https://www.baidu.com/")
      self.driver.set_window_size(1536, 824)
      self.driver.find_element(By.ID, "kw").click()
      self.driver.find_element(By.ID, "kw").send_keys("hello world")
      self.driver.find_element(By.ID, "su").click()
      element = self.driver.find_element(By.ID, "su")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).perform()
      element = self.driver.find_element(By.CSS_SELECTOR, "body")
      actions = ActionChains(self.driver)
      actions.move_to_element(element, 0, 0).perform()
      element = self.driver.find_element(By.LINK_TEXT, "作者")
      actions = ActionChains(self.driver)
      actions.move_to_element(element).perform()
  
